#This is suppoed to instatly give you the value of the resistor after entering the colours present on the resistor
import tkinter
from Resistance_calculator_backend import Number, colour_codes, resistance_4, resistance_5
from PIL import Image, ImageTk
window= tkinter.Tk()
window.configure(bg="Black")
window.geometry("1000x1000")
window.title("Resistance Colour Code Calculator")
#setting background Image
bg = ImageTk.PhotoImage(file=r"C:\Users\Shruthi\Downloads\background_res.jpg")
bg_label = tkinter.Label(window, image=bg)
bg_label.place(x=0, y=0, relwidth=1, relheight=1)
L1=tkinter.Label(window, text="WELCOME TO RESISTANCE CALUCLULATOR!!",fg="white",bg="black", font=("Comic Sans MS", 20))
L1.pack(padx=20, pady=20)
def calculate(sel) :
    bg_label1.destroy()
    Label0.destroy()
    B1.destroy()
    dropdown1.destroy()
    window.configure(bg="Black")
    current_sel= int(sel.get())
    if current_sel==4 :
        Label1= tkinter.Label(window,text="Select the Colour of the first band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label1.pack(padx=10,pady=10)
        select1= tkinter.StringVar(window)
        select1.set("Select an Option")
        dropdown01 = tkinter.OptionMenu(window, select1, *Colours)
        dropdown01.pack()
    #
        Label2= tkinter.Label(window,text="Select the Colour of the second band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label2.pack(padx=10,pady=10)
        select2= tkinter.StringVar(window)
        select2.set("Select an Option")
        dropdown02 = tkinter.OptionMenu(window, select2, *Colours)
        dropdown02.pack()
    #
        Label3= tkinter.Label(window,text="Select the Colour of the third band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label3.pack(padx=10,pady=10)
        select3= tkinter.StringVar(window)
        select3.set("Select an Option")
        dropdown03 = tkinter.OptionMenu(window, select3, *Colours)
        dropdown03.pack()
    #
        Label4= tkinter.Label(window,text="Select the Colour of the fourth band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label4.pack(padx=10,pady=10)
        select4= tkinter.StringVar(window)
        select4.set("Select an Option")
        dropdown04 = tkinter.OptionMenu(window, select4, *Colours)
        dropdown04.pack()
        def assign() :
            Label1.destroy()
            Label2.destroy()
            Label3.destroy()
            Label4.destroy()
            dropdown01.destroy()
            dropdown02.destroy()
            dropdown03.destroy()
            dropdown04.destroy()
            B.destroy()
            band1= select1.get()
            band2= select2.get()
            mult=select3.get()
            tol=select4.get()
            final= resistance_4(band1,band2,mult,tol)
            L=tkinter.Label(window, text="The resistor value is "+final, fg= "Red", bg="Black", font=("Comic Sans MS", 20))
            L.place(relx=0.5, rely=0.5, anchor='center')
        B=tkinter.Button(window, text="Calculate", command=assign, bg="green", fg="Blue")
        B.pack(padx=10, pady=10)
    
    else :
        Label1= tkinter.Label(window,text="Select the Colour of the first band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label1.pack(padx=10,pady=10)
        select1= tkinter.StringVar(window)
        select1.set("Select an Option")
        dropdown01 = tkinter.OptionMenu(window, select1, *Colours)
        dropdown01.pack()
    #
        Label2= tkinter.Label(window,text="Select the Colour of the second band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label2.pack(padx=10,pady=10)
        select2= tkinter.StringVar(window)
        select2.set("Select an Option")
        dropdown02 = tkinter.OptionMenu(window, select2, *Colours)
        dropdown02.pack()
    #
        Label3= tkinter.Label(window,text="Select the Colour of the third band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label3.pack(padx=10,pady=10)
        select3= tkinter.StringVar(window)
        select3.set("Select an Option")
        dropdown03 = tkinter.OptionMenu(window, select3, *Colours)
        dropdown03.pack()
    #
        Label4= tkinter.Label(window,text="Select the Colour of the fourth band", fg="lightblue", bg="black", font=("Gismo", 12))
        Label4.pack(padx=10,pady=10)
        select4= tkinter.StringVar(window)
        select4.set("Select an Option")
        dropdown04 = tkinter.OptionMenu(window, select4, *Colours)
        dropdown04.pack()
    #
        Label5= tkinter.Label(window,text="Select the Colour of the fifth band", fg="lightblue", bg="black", font=("Comic Sans MS", 12))
        Label5.pack(padx=10,pady=10)
        select5= tkinter.StringVar(window)
        select5.set("Select an Option")
        dropdown05 = tkinter.OptionMenu(window, select5, *Colours)
        dropdown05.pack()
        def assign() :
            Label1.destroy()
            Label2.destroy()
            Label3.destroy()
            Label4.destroy()
            Label5.destroy()
            dropdown01.destroy()
            dropdown02.destroy()
            dropdown03.destroy()
            dropdown04.destroy()
            dropdown05.destroy()
            B.destroy()
            band1= select1.get()
            band2= select2.get()
            band3= select3.get()
            mult=select4.get()
            tol=select5.get()
            #global final
            final= resistance_5(band1,band2,band3,mult,tol)
            L=tkinter.Label(window, text="The resistor value is "+final, fg='Red', bg="black", font=("Comic Sans MS", 20))
            L.place(relx=0.5, rely=0.5, anchor='center')
        B=tkinter.Button(window, text="Calculate", command=assign, bg="green", fg="Blue")
        B.pack(padx=10, pady=10)
def destroy() :
    L1.destroy()
    bg_label.destroy()
    Bu.destroy()
    global bg1
    global bg_label1
    global Label0, dropdown1, B1
    bg1= ImageTk.PhotoImage(file=r"C:\Users\Shruthi\Downloads\background_2.png")
    bg_label1 = tkinter.Label(window, image=bg1)
    bg_label1.place(x=0, y=0, relwidth=1, relheight=1)
    Label0= tkinter.Label(window,text="Select the Number of bands", fg="white", bg="black", font=("Times New Roman", 16))
    Label0.pack(padx=20,pady=20)
    sel= tkinter.IntVar(window)
    sel.set("Select an Option")
    dropdown1=tkinter.OptionMenu(window, sel, *Number)
    dropdown1.pack()
    B1=tkinter.Button(window, text="Next", command=lambda: calculate(sel),bg="white", fg="Blue")
    B1.pack(padx=5, pady=5)
Bu=tkinter.Button(window, text="Let's Go!", command=destroy, bg="white", fg="black", font=("Comic Sans MS", 16))
Bu.pack(padx=20, pady=20)
Colours= list(colour_codes.keys())
#Setting background image for the second window
window.mainloop()
    
